version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app/public
    environment:
      - UPLOAD_FOLDER=public
      - FILE_LIFETIME=60
      - PORT=8080
      - DEBUG=False
    # restart: unless-stopped
